# -*- coding: UTF-8 -*-
COUNTRY_CODE = {
	"BD": {"en":u"Bangladesh", "zh":u"孟加拉", "ja":u"バングラデシュ"},
	"WF": {"en":u"Wallis & Futuna Islands", "zh":u"瓦利斯群島和富圖納群島", "ja":u"ウォリス・フツナ"},
	"BF": {"en":u"Burkina Faso", "zh":u"布其納法索", "ja":u"ブルキナファソ"},
	"BG": {"en":u"Bulgaria", "zh":u"保加利亞", "ja":u"ブルガリア"},
	"BA": {"en":u"Bosnia and Herzegovina", "zh":u"波斯尼亞和黑塞哥維那", "ja":u"ボスニア・ヘルツェゴビナ"},
	"BB": {"en":u"Barbados", "zh":u"巴巴多斯", "ja":u"バルバドス"},
	"BE": {"en":u"Belgium", "zh":u"比利時", "ja":u"ベルギー"},
	"BL": {"en":u"Saint Barthélemy", "zh":u"聖巴瑟米", "ja":u"サン・バルテルミー島"},
	"BM": {"en":u"Bermuda", "zh":u"百慕達", "ja":u"バミューダ諸島"},
	"BN": {"en":u"Brunei Darussalam", "zh":u"汶萊", "ja":u"ブルネイ"},
	"BO": {"en":u"Bolivia", "zh":u"玻利維亞", "ja":u"ボリビア"},
	"JP": {"en":u"Japan", "zh":u"日本", "ja":u"日本"},
	"BI": {"en":u"Burundi", "zh":u"布隆迪", "ja":u"ブルンジ"},
	"BJ": {"en":u"Benin", "zh":u"貝寧", "ja":u"ベナン"},
	"BT": {"en":u"Bhutan", "zh":u"不丹", "ja":u"ブータン"},
	"JM": {"en":u"Jamaica", "zh":u"牙買加", "ja":u"ジャマイカ"},
	"BV": {"en":u"Bouvet Island", "zh":u"布維島", "ja":u"ブーベ島"},
	"BW": {"en":u"Botswana", "zh":u"博茨瓦納", "ja":u"ボツワナ"},
	"WS": {"en":u"Samoa", "zh":u"薩摩亞", "ja":u"サモア"},
	"BQ": {"en":u"Caribbean Netherlands", "zh":u"荷蘭加勒比區", "ja":u"ボネール、シント・ユースタティウスおよびサバ"},
	"BR": {"en":u"Brazil", "zh":u"巴西", "ja":u"ブラジル"},
	"BS": {"en":u"Bahama", "zh":u"巴哈馬", "ja":u"バハマ"},
	"JE": {"en":u"Jersey", "zh":u"澤西島", "ja":u"ジャージー"},
	"BY": {"en":u"Belarus", "zh":u"白俄羅斯", "ja":u"ベラルーシ"},
	"BZ": {"en":u"Belize", "zh":u"伯利茲", "ja":u"ベリーズ"},
	"RU": {"en":u"Russian Federation", "zh":u"俄羅斯聯邦", "ja":u"ロシア"},
	"RW": {"en":u"Rwanda", "zh":u"盧旺達", "ja":u"ルワンダ"},
	"RS": {"en":u"Serbia", "zh":u"塞爾維亞", "ja":u"セルビア"},
	"TL": {"en":u"Timor-Leste", "zh":u"東帝汶", "ja":u"東ティモール"},
	"RE": {"en":u"Réunion", "zh":u"留尼汪", "ja":u"レユニオン"},
	"TM": {"en":u"Turkmenistan", "zh":u"土庫曼斯坦", "ja":u"トルクメニスタン"},
	"TJ": {"en":u"Tajikistan", "zh":u"塔吉克斯坦", "ja":u"タジキスタン"},
	"RO": {"en":u"Romania", "zh":u"羅馬尼亞", "ja":u"ルーマニア"},
	"TK": {"en":u"Tokelau", "zh":u"托克勞", "ja":u"トケラウ"},
	"GW": {"en":u"Guinea-Bissau", "zh":u"幾內亞比紹", "ja":u"ギニアビサウ"},
	"GU": {"en":u"Guam", "zh":u"關島", "ja":u"グアム"},
	"GT": {"en":u"Guatemala", "zh":u"危地馬拉", "ja":u"グアテマラ"},
	"GS": {"en":u"South Georgia and the South Sandwich Islands", "zh":u"南喬治亞島和南桑威奇群島", "ja":u"サウスジョージア・サウスサンドウィッチ諸島"},
	"GR": {"en":u"Greece", "zh":u"希臘", "ja":u"ギリシャ"},
	"GQ": {"en":u"Equatorial Guinea", "zh":u"赤道幾內亞", "ja":u"赤道ギニア"},
	"GP": {"en":u"Guadeloupe", "zh":u"瓜德羅普島", "ja":u"グアドループ"},
	"BH": {"en":u"Bahrain", "zh":u"巴林", "ja":u"バーレーン"},
	"GY": {"en":u"Guyana", "zh":u"圭亞那", "ja":u"ガイアナ"},
	"GG": {"en":u"Guernsey", "zh":u"根西島", "ja":u"ガーンジー"},
	"GF": {"en":u"French Guiana", "zh":u"法屬圭亞那", "ja":u"フランス領ギアナ"},
	"GE": {"en":u"Georgia", "zh":u"格魯吉亞", "ja":u"グルジア"},
	"GD": {"en":u"Grenada", "zh":u"格林納達", "ja":u"グレナダ"},
	"GB": {"en":u"United Kingdom", "zh":u"英國", "ja":u"イギリス"},
	"GA": {"en":u"Gabon", "zh":u"加蓬", "ja":u"ガボン"},
	"SV": {"en":u"El Salvador", "zh":u"薩爾瓦多", "ja":u"エルサルバドル"},
	"GN": {"en":u"Guinea", "zh":u"幾內亞", "ja":u"ギニア"},
	"GM": {"en":u"Gambia", "zh":u"岡比亞", "ja":u"ガンビア"},
	"GL": {"en":u"Greenland", "zh":u"格陵蘭", "ja":u"グリーンランド"},
	"KW": {"en":u"Kuwait", "zh":u"科威特", "ja":u"クウェート"},
	"GI": {"en":u"Gibraltar", "zh":u"直布羅陀", "ja":u"ジブラルタル"},
	"GH": {"en":u"Ghana", "zh":u"加納", "ja":u"ガーナ"},
	"OM": {"en":u"Oman", "zh":u"阿曼", "ja":u"オマーン"},
	"TN": {"en":u"Tunisia", "zh":u"突尼斯", "ja":u"チュニジア"},
	"JO": {"en":u"Jordan", "zh":u"約旦", "ja":u"ヨルダン"},
	"HR": {"en":u"Croatia", "zh":u"克羅地亞", "ja":u"クロアチア"},
	"HT": {"en":u"Haiti", "zh":u"海地", "ja":u"ハイチ"},
	"HU": {"en":u"Hungary", "zh":u"匈牙利", "ja":u"ハンガリー"},
	"HK": {"en":u"Hong Kong", "zh":u"香港", "ja":u"香港"},
	"HN": {"en":u"Honduras", "zh":u"洪都拉斯", "ja":u"ホンジュラス"},
	"HM": {"en":u"Heard & McDonald Islands", "zh":u"赫德和麥克唐納群島", "ja":u"ハード島とマクドナルド諸島"},
	"CR": {"en":u"Costa Rica", "zh":u"哥斯達黎加", "ja":u"コスタリカ"},
	"AD": {"en":u"Andorra", "zh":u"安道爾", "ja":u"アンドラ"},
	"PR": {"en":u"Puerto Rico", "zh":u"波多黎各", "ja":u"プエルトリコ"},
	"PS": {"en":u"Palestinian", "zh":u"巴勒斯坦", "ja":u"パレスチナ"},
	"PW": {"en":u"Palau", "zh":u"帕勞", "ja":u"パラオ"},
	"PT": {"en":u"Portugal", "zh":u"葡萄牙", "ja":u"ポルトガル"},
	"SJ": {"en":u"Svalbard & Jan Mayen Islands", "zh":u"斯瓦爾巴群島和揚馬延島", "ja":u"スヴァールバル諸島およびヤンマイエン島"},
	"PY": {"en":u"Paraguay", "zh":u"巴拉圭", "ja":u"パラグアイ"},
	"IQ": {"en":u"Iraq", "zh":u"伊拉克", "ja":u"イラク"},
	"PA": {"en":u"Panama", "zh":u"巴拿馬", "ja":u"パナマ"},
	"PF": {"en":u"French Polynesia", "zh":u"法屬波利尼西亞", "ja":u"フランス領ポリネシア"},
	"PG": {"en":u"Papua New Guinea", "zh":u"巴布亞新幾內亞", "ja":u"パプアニューギニア"},
	"PE": {"en":u"Peru", "zh":u"秘魯", "ja":u"ペルー"},
	"PK": {"en":u"Pakistan", "zh":u"巴基斯坦", "ja":u"パキスタン"},
	"PH": {"en":u"Philippines", "zh":u"菲律賓", "ja":u"フィリピン"},
	"PN": {"en":u"Pitcairn", "zh":u"皮特凱恩", "ja":u"ピトケアン"},
	"PL": {"en":u"Poland", "zh":u"波蘭", "ja":u"ポーランド"},
	"PM": {"en":u"St. Pierre & Miquelon", "zh":u"聖皮埃爾和密克隆群島", "ja":u"サンピエール島・ミクロン島"},
	"ZM": {"en":u"Zambia", "zh":u"贊比亞", "ja":u"ザンビア"},
	"EH": {"en":u"Western Sahara", "zh":u"西撒哈拉", "ja":u"西サハラ"},
	"EE": {"en":u"Estonia", "zh":u"愛沙尼亞", "ja":u"エストニア"},
	"EG": {"en":u"Egypt", "zh":u"埃及", "ja":u"エジプト"},
	"ZA": {"en":u"South Africa", "zh":u"南非", "ja":u"南アフリカ"},
	"EC": {"en":u"Ecuador", "zh":u"厄瓜多爾", "ja":u"エクアドル"},
	"AL": {"en":u"Albania", "zh":u"阿爾巴尼亞", "ja":u"アルバニア"},
	"AO": {"en":u"Angola", "zh":u"安哥拉", "ja":u"アンゴラ"},
	"KZ": {"en":u"Kazakhstan", "zh":u"哈薩克斯坦", "ja":u"カザフスタン"},
	"ET": {"en":u"Ethiopia", "zh":u"埃塞俄比亞", "ja":u"エチオピア"},
	"ZW": {"en":u"Zimbabwe", "zh":u"津巴布韋", "ja":u"ジンバブエ"},
	"SA": {"en":u"Saudi Arabia", "zh":u"沙特阿拉伯", "ja":u"サウジアラビア"},
	"ES": {"en":u"Spain", "zh":u"西班牙", "ja":u"スペイン"},
	"ER": {"en":u"Eritrea", "zh":u"厄立特里亞", "ja":u"エリトリア"},
	"ME": {"en":u"Montenegro", "zh":u"黑山", "ja":u"モンテネグロ"},
	"MD": {"en":u"Moldova", "zh":u"摩爾多瓦", "ja":u"モルドバ"},
	"MG": {"en":u"Madagascar", "zh":u"馬達加斯加", "ja":u"マダガスカル"},
	"MF": {"en":u"Saint Martin", "zh":u"法屬聖馬丁", "ja":u"サン・マルタン島"},
	"UY": {"en":u"Uruguay", "zh":u"烏拉圭", "ja":u"ウルグアイ"},
	"MC": {"en":u"Monaco", "zh":u"摩納哥", "ja":u"モナコ"},
	"UZ": {"en":u"Uzbekistan", "zh":u"烏茲別克斯坦", "ja":u"ウズベキスタン"},
	"MM": {"en":u"Myanmar", "zh":u"緬甸", "ja":u"ミャンマー"},
	"ML": {"en":u"Mali", "zh":u"馬里", "ja":u"マリ"},
	"MO": {"en":u"Macau", "zh":u"澳門", "ja":u"マカオ"},
	"MN": {"en":u"Mongolia", "zh":u"蒙古", "ja":u"モンゴル"},
	"MH": {"en":u"Marshall Islands", "zh":u"馬紹爾群島", "ja":u"マーシャル諸島"},
	"US": {"en":u"United States of America", "zh":u"美國", "ja":u"アメリカ合衆国"},
	"UM": {"en":u"United States Minor Outlying Islands", "zh":u"美國本土外小島嶼", "ja":u"合衆国領有小離島"},
	"MT": {"en":u"Malta", "zh":u"馬爾他", "ja":u"マルタ"},
	"MW": {"en":u"Malawi", "zh":u"馬拉威", "ja":u"マラウイ"},
	"MV": {"en":u"Maldives", "zh":u"馬爾地夫", "ja":u"モルディブ"},
	"MQ": {"en":u"Martinique", "zh":u"馬提尼克", "ja":u"マルティニーク"},
	"MP": {"en":u"Northern Mariana Islands", "zh":u"北馬里亞納群島", "ja":u"北マリアナ諸島"},
	"MS": {"en":u"Monserrat", "zh":u"蒙特塞拉特", "ja":u"モントセラト"},
	"MR": {"en":u"Mauritania", "zh":u"毛里塔尼亞", "ja":u"モーリタニア"},
	"AU": {"en":u"Australia", "zh":u"澳大利亞", "ja":u"オーストラリア"},
	"UG": {"en":u"Uganda", "zh":u"烏干達", "ja":u"ウガンダ"},
	"UA": {"en":u"Ukraine", "zh":u"烏克蘭", "ja":u"ウクライナ"},
	"MX": {"en":u"Mexico", "zh":u"墨西哥", "ja":u"メキシコ"},
	"VU": {"en":u"Vanuatu", "zh":u"瓦努阿圖", "ja":u"バヌアツ"},
	"FR": {"en":u"France", "zh":u"法國", "ja":u"フランス"},
	"AW": {"en":u"Aruba", "zh":u"阿魯巴", "ja":u"アルバ"},
	"SH": {"en":u"St. Helena", "zh":u"聖赫勒拿", "ja":u"セントヘレナ・アセンションおよびトリスタン・ダ・クーニャ"},
	"AX": {"en":u"Åaland Island", "zh":u"奧蘭群島", "ja":u"オーランド諸島"},
	"FI": {"en":u"Finland", "zh":u"芬蘭", "ja":u"フィンランド"},
	"FJ": {"en":u"Fiji", "zh":u"斐濟", "ja":u"フィジー"},
	"FK": {"en":u"Falkland Islands", "zh":u"福克蘭群島", "ja":u"フォークランド諸島"},
	"FM": {"en":u"Micronesia", "zh":u"密克羅尼西亞", "ja":u"ミクロネシア連邦"},
	"FO": {"en":u"Faroe Islands", "zh":u"法羅群島", "ja":u"フェロー諸島"},
	"NI": {"en":u"Nicaragua", "zh":u"尼加拉瓜", "ja":u"ニカラグア"},
	"NL": {"en":u"Netherlands", "zh":u"荷蘭", "ja":u"オランダ"},
	"NO": {"en":u"Norway", "zh":u"挪威", "ja":u"ノルウェー"},
	"NA": {"en":u"Namibia", "zh":u"納米比亞", "ja":u"ナミビア"},
	"NC": {"en":u"New Caledonia", "zh":u"新喀裡多尼亞", "ja":u"ニューカレドニア"},
	"NE": {"en":u"Niger", "zh":u"尼日爾", "ja":u"ニジェール"},
	"NF": {"en":u"Norfolk Island", "zh":u"諾福克島", "ja":u"ノーフォーク島"},
	"NG": {"en":u"Nigeria", "zh":u"尼日利亞", "ja":u"ナイジェリア"},
	"NZ": {"en":u"New Zealand", "zh":u"紐西蘭", "ja":u"ニュージーランド"},
	"NP": {"en":u"Nepal", "zh":u"尼泊爾", "ja":u"ネパール"},
	"NR": {"en":u"Nauru", "zh":u"瑙魯", "ja":u"ナウル"},
	"NU": {"en":u"Niue", "zh":u"紐埃", "ja":u"ニウエ"},
	"CK": {"en":u"Cook Iislands", "zh":u"庫克群島", "ja":u"クック諸島"},
	"XK": {"en":u"Kosovo", "zh":u"科索沃", "ja":u"コソボ"},
	"CI": {"en":u"Ivory Coast", "zh":u"象牙海岸", "ja":u"コートジボワール"},
	"CH": {"en":u"Switzerland", "zh":u"瑞士", "ja":u"スイス"},
	"CO": {"en":u"Colombia", "zh":u"哥倫比亞", "ja":u"コロンビア"},
	"CN": {"en":u"China", "zh":u"中國", "ja":u"中華人民共和国"},
	"CM": {"en":u"Cameroon", "zh":u"喀麥隆", "ja":u"カメルーン"},
	"CL": {"en":u"Chile", "zh":u"智利", "ja":u"チリ"},
	"CC": {"en":u"Cocos Islands", "zh":u"可可島", "ja":u"ココス諸島"},
	"CA": {"en":u"Canada", "zh":u"加拿大", "ja":u"カナダ"},
	"CG": {"en":u"Congo", "zh":u"剛果", "ja":u"コンゴ共和国"},
	"CF": {"en":u"Central African Republic", "zh":u"中非共和國", "ja":u"中央アフリカ"},
	"CD": {"en":u"Democratic Republic of the Congo", "zh":u"民主剛果", "ja":u"コンゴ民主共和国"},
	"CZ": {"en":u"Czech Republic", "zh":u"捷克共和國", "ja":u"チェコ"},
	"CY": {"en":u"Cyprus", "zh":u"塞浦路斯", "ja":u"キプロス"},
	"CX": {"en":u"Christmas Island", "zh":u"聖誕島", "ja":u"クリスマス島"},
	"MA": {"en":u"Morocco", "zh":u"摩洛哥", "ja":u"モロッコ"},
	"CW": {"en":u"Curaçao", "zh":u"庫拉索島", "ja":u"キュラソー"},
	"CV": {"en":u"Cape Verde", "zh":u"佛得角", "ja":u"カーボベルデ"},
	"CU": {"en":u"Cuba", "zh":u"古巴", "ja":u"キューバ"},
	"SZ": {"en":u"Swaziland", "zh":u"史瓦濟蘭", "ja":u"スワジランド"},
	"SY": {"en":u"Syrian Arab Republic", "zh":u"敘利亞", "ja":u"シリア"},
	"SX": {"en":u"Sint Maarten", "zh":u"荷屬聖馬丁", "ja":u"シント・マールテン島"},
	"KG": {"en":u"Kyrgyzstan", "zh":u"吉爾吉斯斯坦", "ja":u"キルギス"},
	"KE": {"en":u"Kenya", "zh":u"肯亞", "ja":u"ケニア"},
	"SS": {"en":u"South Sudan", "zh":u"南蘇丹", "ja":u"南スーダン"},
	"SR": {"en":u"Suriname", "zh":u"蘇里南", "ja":u"スリナム"},
	"KI": {"en":u"Kiribati", "zh":u"基里巴斯", "ja":u"キリバス"},
	"KH": {"en":u"Cambodia", "zh":u"柬埔寨", "ja":u"カンボジア"},
	"KN": {"en":u"St. Kitts and Nevis", "zh":u"聖基茨和尼維斯", "ja":u"セントクリストファー・ネイビス"},
	"KM": {"en":u"Comoros", "zh":u"科摩羅", "ja":u"コモロ"},
	"ST": {"en":u"Sao Tome & Principe", "zh":u"聖多美和普林西比", "ja":u"サントメ・プリンシペ"},
	"SK": {"en":u"Slovakia", "zh":u"斯洛伐克", "ja":u"スロバキア"},
	"KR": {"en":u"Korea", "zh":u"韓國", "ja":u"大韓民国"},
	"SI": {"en":u"Slovenia", "zh":u"斯洛文尼亞", "ja":u"スロベニア"},
	"KP": {"en":u"North Korea", "zh":u"朝鮮", "ja":u"朝鮮民主主義人民共和国"},
	"SO": {"en":u"Somalia", "zh":u"索馬里", "ja":u"ソマリア"},
	"SN": {"en":u"Senegal", "zh":u"塞內加爾", "ja":u"セネガル"},
	"SM": {"en":u"San Marino", "zh":u"聖馬力諾", "ja":u"サンマリノ"},
	"SL": {"en":u"Sierra Leone", "zh":u"塞拉利昂", "ja":u"シエラレオネ"},
	"SC": {"en":u"Seychelles", "zh":u"塞舌爾", "ja":u"セーシェル"},
	"SB": {"en":u"Solomon Islands", "zh":u"所羅門群島", "ja":u"ソロモン諸島"},
	"KY": {"en":u"Cayman Islands", "zh":u"開曼群島", "ja":u"ケイマン諸島"},
	"SG": {"en":u"Singapore", "zh":u"新加坡", "ja":u"シンガポール"},
	"SE": {"en":u"Sweden", "zh":u"瑞典", "ja":u"スウェーデン"},
	"SD": {"en":u"Sudan", "zh":u"蘇丹", "ja":u"スーダン"},
	"DO": {"en":u"Dominican Republic", "zh":u"多米尼加共和國", "ja":u"ドミニカ共和国"},
	"DM": {"en":u"Dominica", "zh":u"多米尼加", "ja":u"ドミニカ国"},
	"DJ": {"en":u"Djibouti", "zh":u"吉布提", "ja":u"ジブチ"},
	"DK": {"en":u"Denmark", "zh":u"丹麥", "ja":u"デンマーク"},
	"VG": {"en":u"British Virgin Islands", "zh":u"英屬維爾京群島", "ja":u"イギリス領ヴァージン諸島"},
	"DE": {"en":u"Germany", "zh":u"德國", "ja":u"ドイツ"},
	"YE": {"en":u"Yemen", "zh":u"葉門", "ja":u"イエメン"},
	"AT": {"en":u"Austria", "zh":u"奧地利", "ja":u"オーストリア"},
	"DZ": {"en":u"Algeria", "zh":u"阿爾及利亞", "ja":u"アルジェリア"},
	"MK": {"en":u"Republic of Macedonia", "zh":u"馬其頓", "ja":u"マケドニア共和国"},
	"YT": {"en":u"Mayotte", "zh":u"馬約特", "ja":u"マヨット"},
	"MU": {"en":u"Mauritius", "zh":u"毛里求斯", "ja":u"モーリシャス"},
	"LB": {"en":u"Lebanon", "zh":u"黎巴嫩", "ja":u"レバノン"},
	"LC": {"en":u"Saint Lucia", "zh":u"聖盧西亞", "ja":u"セントルシア"},
	"LA": {"en":u"Lao People's Democratic Republic", "zh":u"寮國", "ja":u"ラオス"},
	"TV": {"en":u"Tuvalu", "zh":u"圖瓦盧", "ja":u"ツバル"},
	"TW": {"en":u"Taiwan", "zh":u"台灣", "ja":u"台湾（台湾省/中華民国）"},
	"TT": {"en":u"Trinidad & Tobago", "zh":u"特立尼達和多巴哥", "ja":u"トリニダード・トバゴ"},
	"TR": {"en":u"Turkey", "zh":u"土耳其", "ja":u"トルコ"},
	"LK": {"en":u"Sri Lanka", "zh":u"斯里蘭卡", "ja":u"スリランカ"},
	"LI": {"en":u"Liechtenstein", "zh":u"列支敦士登", "ja":u"リヒテンシュタイン"},
	"LV": {"en":u"Latvia", "zh":u"拉托維亞", "ja":u"ラトビア"},
	"TO": {"en":u"Tonga", "zh":u"東加", "ja":u"トンガ"},
	"LT": {"en":u"Lithuania", "zh":u"立陶宛", "ja":u"リトアニア"},
	"LU": {"en":u"Luxembourg", "zh":u"盧森堡", "ja":u"ルクセンブルク"},
	"LR": {"en":u"Liberia", "zh":u"利比里亞", "ja":u"リベリア"},
	"LS": {"en":u"Lesotho", "zh":u"萊索托", "ja":u"レソト"},
	"TH": {"en":u"Thailand", "zh":u"泰國", "ja":u"タイ"},
	"TF": {"en":u"French Southern Territories", "zh":u"法國南部領土", "ja":u"フランス領南方・南極地域"},
	"TG": {"en":u"Togo", "zh":u"多哥", "ja":u"トーゴ"},
	"TD": {"en":u"Chad", "zh":u"查德", "ja":u"チャド"},
	"TC": {"en":u"Turks & Caicos Islands", "zh":u"特克斯和凱科斯群島", "ja":u"タークス・カイコス諸島"},
	"LY": {"en":u"Libyan Arab Jamahiriya", "zh":u"利比亞", "ja":u"リビア"},
	"VA": {"en":u"Vatican", "zh":u"梵蒂岡", "ja":u"バチカン"},
	"VC": {"en":u"St. Vincent & the Grenadines", "zh":u"聖文森特和格林納丁斯", "ja":u"セントビンセント・グレナディーン"},
	"AE": {"en":u"United Arab Emirates", "zh":u"阿拉伯", "ja":u"アラブ首長国連邦"},
	"VE": {"en":u"Venezuela", "zh":u"委內瑞拉", "ja":u"ベネズエラ"},
	"AG": {"en":u"Antigua & Barbuda", "zh":u"安提瓜和巴布達", "ja":u"アンティグア・バーブーダ"},
	"AF": {"en":u"Afghanistan", "zh":u"阿富汗", "ja":u"アフガニスタン"},
	"AI": {"en":u"Anguilla", "zh":u"安圭拉", "ja":u"アンギラ"},
	"VI": {"en":u"United States Virgin Islands", "zh":u"美屬維爾京群島", "ja":u"アメリカ領ヴァージン諸島"},
	"IS": {"en":u"Iceland", "zh":u"冰島", "ja":u"アイスランド"},
	"IR": {"en":u"Islamic Republic of Iran", "zh":u"伊朗伊斯蘭共和國", "ja":u"イラン"},
	"AM": {"en":u"Armenia", "zh":u"亞美尼亞", "ja":u"アルメニア"},
	"IT": {"en":u"Italy", "zh":u"義大利", "ja":u"イタリア"},
	"VN": {"en":u"Viet Nam", "zh":u"越南", "ja":u"ベトナム"},
	"AQ": {"en":u"Antarctica", "zh":u"南極洲", "ja":u"南極"},
	"AS": {"en":u"American Samoa", "zh":u"美屬薩摩亞", "ja":u"アメリカ領サモア"},
	"AR": {"en":u"Argentina", "zh":u"阿根廷", "ja":u"アルゼンチン"},
	"IM": {"en":u"Isle of Man", "zh":u"曼島", "ja":u"マン島"},
	"IL": {"en":u"Israel", "zh":u"以色列", "ja":u"イスラエル"},
	"IO": {"en":u"British Indian Ocean Territory", "zh":u"英屬印度洋領地", "ja":u"イギリス領インド洋地域"},
	"IN": {"en":u"India", "zh":u"印度", "ja":u"インド"},
	"TZ": {"en":u"Tanzania", "zh":u"坦桑尼亞聯合共和國", "ja":u"タンザニア"},
	"AZ": {"en":u"Azerbaijan", "zh":u"阿塞拜疆", "ja":u"アゼルバイジャン"},
	"IE": {"en":u"Ireland", "zh":u"愛爾蘭", "ja":u"アイルランド"},
	"ID": {"en":u"Indonesia", "zh":u"印度尼西亞", "ja":u"インドネシア"},
	"MY": {"en":u"Malaysia", "zh":u"馬來西亞", "ja":u"マレーシア"},
	"QA": {"en":u"Qatar", "zh":u"卡塔爾", "ja":u"カタール"},
	"MZ": {"en":u"Mozambique", "zh":u"莫桑比克", "ja":u"モザンビーク"},
}